package com.chain.wp.restapi.entity;

import java.io.Serializable;

public class CommentUserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wp_comment_user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wp_comment_user_info.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wp_comment_user_info.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * wp_comment_user_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column wp_comment_user_info.id
     *
     * @return the value of wp_comment_user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wp_comment_user_info.id
     *
     * @param id the value for wp_comment_user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column wp_comment_user_info.mail
     *
     * @return the value of wp_comment_user_info.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wp_comment_user_info.mail
     *
     * @param mail the value for wp_comment_user_info.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column wp_comment_user_info.nickname
     *
     * @return the value of wp_comment_user_info.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wp_comment_user_info.nickname
     *
     * @param nickname the value for wp_comment_user_info.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
}
