#==================== wordpress ============================
wordpress:
    post:
        home:
            desc: 首页所有内容封装
            postUrl: https://www.chainage.jp/wp-json/wp/v2/posts
            tagUrl: https://www.chainage.jp/wp-json/wp/v2/tags
            userUrl: https://www.chainage.jp/wp-json/wp/v2/users
            categoryUrl: https://www.chainage.jp/wp-json/wp/v2/categories
            mediaUrl: https://www.chainage.jp/wp-json/wp/v2/media
            listmap:
                - categories: 100
                  per_page: 3
                  order: desc
                  orderby: date
                  status: publish
                  active: true
                - categories: 103
                  per_page: 6
                  order: desc
                  orderby: date
                  status: publish
                  active: true
                - categories: 148
                  per_page: 6
                  order: desc
                  orderby: date
                  status: publish
                  active: true
                - categories: 99
                  per_page: 10
                  order: desc
                  orderby: date
                  status: publish
                  active: true