#==================== wordpress ============================
wordpress:
  post:
    home:
      desc: 首页所有内容封装
      postUrl: http://chainage.cc/wp-json/wp/v2/posts
      tagUrl: http://chainage.cc/wp-json/wp/v2/tags
      userUrl: http://chainage.cc/wp-json/wp/v2/users
      categoryUrl: http://chainage.cc/wp-json/wp/v2/categories
      mediaUrl: http://chainage.cc/wp-json/wp/v2/media
      listmap:
        - categories: 180
          per_page: 3
          order: desc
          orderby: date
          status: publish
          thumbnail: 700,400
          desc: 首页上方轮播
          active: true
        - categories: 181
          per_page: 3
          order: desc
          orderby: date
          status: publish
          thumbnail: 300,150
          desc: 轮播图下方告栏
          active: true
        - categories: 99
          per_page: 6
          order: desc
          orderby: date
          status: publish
          thumbnail: 300,150
          desc: 首页新闻模块
          active: true
        - categories: 186
          per_page: 1
          order: desc
          orderby: date
          status: publish
          thumbnail: 1920,400
          desc: 首页第1个广告栏
          active: true
        - categories: 184
          per_page: 6
          order: desc
          orderby: date
          status: publish
          thumbnail: 300,150
          desc: 首页特集模块
          active: true
        - categories: 187
          per_page: 1
          order: desc
          orderby: date
          status: publish
          thumbnail: 1920,400
          desc: 首页第2个广告栏
          active: true
        - categories: 185
          per_page: 6
          order: desc
          orderby: date
          status: publish
          thumbnail: 300,150
          desc: 首页chaiange channel
          active: true
    finance: 
      id: 6137
      desc: 财政厅文章模块
    rightpopular:
      id: 6374
      thumbnail: 300,300
      desc: 新闻内容页右侧热点文章模块
    ctrecommend:
      thumbnail: 300,150
      expire-time: 300
      desc: 新闻内容页下方文章推荐模块
      
#==================== coin ============================
coin:
  job:
    api-key-name: X-CMC_PRO_API_KEY
    api-key-value: 36e73e36-c202-4f0e-8f17-0190aa8a0705
    #setAssetsQuotationRateCurrent_Job()方法所用到的参数
    assets-quotation-rate-current:
      url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest
      id_base: BTC,BCH,ETH,ETC,XRP,EOS,MIOTA,XLM,LTC,ADA,XMR,DASH,TRX,NEO,XEM,VET
      id_quote: JPY
    #setTopFloatingExchange_Job所用到的参数
    top-floating-exchange:
      url: https://pro-api.coinmarketcap.com/v1/exchange/listings/latest
      sort: volume_24h
      sort_dir_desc: desc
      sort_dir_asc: asc
      market_type: all
      convert: BTC,JPY
      limit: 50
    #setMarkInfoExchange_Job所用到的参数
    mark-info-exchange-job:
      url: https://pro-api.coinmarketcap.com/v1/exchange/market-pairs/latest
      convert: BTC
      limit: 500
    #setMarketInfoExchange所用到的参数
    market-info-exchange:
      url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/market-pairs/latest
      convert: BTC
      limit: 501
    #setBtcMonitorLine_OHLCV所用到的参数
    btc-monitor-line-OHLCV:
      line:
        url: https://pro-api.coinmarketcap.com/v1/tools/price-conversion
        symbol: BTC
        convert: JPY,USD,EUR,CNY
        amount: 1
      ohlcv:
        url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/ohlcv/latest
        symbol: BTC
        convert: JPY
    #setBtcMonitorRate所用到的参数
    btc-monitor-rate:
      url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?
      symbol: BTC
      convert: AUD,EUR,CNY,KRW,JPY,USD
    #setAssetsGeneral_Job所用到的参数
    assets-general-job:
      url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
      convert: JPY
      limit: 500
      sort: price
      sort_dir: asc
    oneday-hour-cap-job:
      url: https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest
      convert: JPY,USD