package com.chain.wp.restapi.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;

import com.chain.wp.restapi.entity.CommentUserInfo;

@Mapper
public interface CommentUserInfoMapper{
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * wp_comment_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * wp_comment_user_info
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(CommentUserInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * wp_comment_user_info
     *
     * @mbggenerated
     */
    CommentUserInfo selectByPrimaryKey(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    int insertSelective(CommentUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentUserInfo record);
    /**
     * 
     * @param record
     * @return
     */
    int selectOne(CommentUserInfo record);
}
