package com.chain.wp.coin.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import com.chain.base.dao.BaseMapper;
import com.chain.wp.coin.entity.Asset;

@Mapper
public interface AssetMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cc_asset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("symbol") String symbol);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * cc_asset
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(Asset record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    int insertSelective(Asset record);

    Asset selectByPrimaryKey(Integer id, String symbol);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Asset record);

    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Asset record);
}
