package com.chain.wp.coin.dao;

import java.util.LinkedHashMap;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import com.chain.wp.coin.entity.Asset;

@Mapper
public interface AssetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("symbol") String symbol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(Asset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    int insertSelective(Asset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    Asset selectByPrimaryKey(@Param("id") Integer id, @Param("symbol") String symbol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Asset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Asset record);
    
    /**
     * 执行任意一条sql
     * @param sql
     * @return
     */
    List<LinkedHashMap<String, Object>> superManagerSelect(String sql);
}