package com.chain.wp.coin.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;

import com.chain.wp.coin.entity.BtcMonitorLineHistory;

@Mapper
public interface BtcMonitorLineHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(BtcMonitorLineHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    int insertSelective(BtcMonitorLineHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    BtcMonitorLineHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BtcMonitorLineHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BtcMonitorLineHistory record);
}