package com.chain.wp.coin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.chain.wp.coin.entity.FloatExchange;

@Mapper
public interface FloatExchangeMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_float_exchange
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_float_exchange
   *
   * @mbggenerated
   */
  int insert(FloatExchange record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_float_exchange
   *
   * @mbggenerated
   */
  int insertSelective(FloatExchange record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_float_exchange
   *
   * @mbggenerated
   */
  FloatExchange selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_float_exchange
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(FloatExchange record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_float_exchange
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(FloatExchange record);

  /**
   * 
   * @param floatExchangeList
   */
  void insertByBatch(List<FloatExchange> floatExchangeList);
}
