package com.chain.wp.coin.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;

import com.chain.wp.coin.entity.LegalCurrency;

@Mapper
public interface LegalCurrencyMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_legalcurrency
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_legalcurrency
   *
   * @mbggenerated
   */
  @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
  int insert(LegalCurrency record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_legalcurrency
   *
   * @mbggenerated
   */
  int insertSelective(LegalCurrency record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_legalcurrency
   *
   * @mbggenerated
   */
  LegalCurrency selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_legalcurrency
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(LegalCurrency record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_legalcurrency
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(LegalCurrency record);
}