package com.chain.wp.coin.dao;

import org.apache.ibatis.annotations.Mapper;

import com.chain.wp.coin.entity.SpecificRate;

@Mapper
public interface SpecificRateMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_specific_rate
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_specific_rate
   *
   * @mbggenerated
   */
  int insert(SpecificRate record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_specific_rate
   *
   * @mbggenerated
   */
  int insertSelective(SpecificRate record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_specific_rate
   *
   * @mbggenerated
   */
  SpecificRate selectByPrimaryKey(String id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_specific_rate
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(SpecificRate record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * cc_specific_rate
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(SpecificRate record);
}
