package com.chain.wp.coin.dao;

import com.chain.wp.coin.entity.Symbol;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SymbolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_symbol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("symbolId") String symbolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_symbol
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(Symbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_symbol
     *
     * @mbggenerated
     */
    int insertSelective(Symbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_symbol
     *
     * @mbggenerated
     */
    Symbol selectByPrimaryKey(@Param("id") Integer id, @Param("symbolId") String symbolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_symbol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Symbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_symbol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Symbol record);
}