package com.chain.wp.coin.entity;

import java.io.Serializable;

public class Asset implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_asset.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_asset.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_asset.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_asset.is_active
     *
     * @mbggenerated
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_asset.logo_img
     *
     * @mbggenerated
     */
    private String logoImg;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_asset.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * cc_asset
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_asset.id
     *
     * @return the value of cc_asset.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_asset.id
     *
     * @param id the value for cc_asset.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_asset.symbol
     *
     * @return the value of cc_asset.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_asset.symbol
     *
     * @param symbol the value for cc_asset.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_asset.name
     *
     * @return the value of cc_asset.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_asset.name
     *
     * @param name the value for cc_asset.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_asset.is_active
     *
     * @return the value of cc_asset.is_active
     *
     * @mbggenerated
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_asset.is_active
     *
     * @param isActive the value for cc_asset.is_active
     *
     * @mbggenerated
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive == null ? null : isActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_asset.logo_img
     *
     * @return the value of cc_asset.logo_img
     *
     * @mbggenerated
     */
    public String getLogoImg() {
        return logoImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_asset.logo_img
     *
     * @param logoImg the value for cc_asset.logo_img
     *
     * @mbggenerated
     */
    public void setLogoImg(String logoImg) {
        this.logoImg = logoImg == null ? null : logoImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_asset.sort
     *
     * @return the value of cc_asset.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_asset.sort
     *
     * @param sort the value for cc_asset.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}
