package com.chain.wp.coin.entity;

import java.io.Serializable;
import java.util.Date;

public class Asset implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.slug
     *
     * @mbggenerated
     */
    private String slug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.num_market_pairs
     *
     * @mbggenerated
     */
    private String numMarketPairs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.circulating_supply
     *
     * @mbggenerated
     */
    private String circulatingSupply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.total_supply
     *
     * @mbggenerated
     */
    private String totalSupply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.max_supply
     *
     * @mbggenerated
     */
    private String maxSupply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.quote_price
     *
     * @mbggenerated
     */
    private String quotePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.quote_volume_24h
     *
     * @mbggenerated
     */
    private String quoteVolume24h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.quote_percent_change_1h
     *
     * @mbggenerated
     */
    private String quotePercentChange1h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.quote_percent_change_24h
     *
     * @mbggenerated
     */
    private String quotePercentChange24h;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.quote_percent_change_7d
     *
     * @mbggenerated
     */
    private String quotePercentChange7d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.quote_market_cap
     *
     * @mbggenerated
     */
    private String quoteMarketCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_asset.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cc_asset
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.id
     *
     * @return the value of cc_asset.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.id
     *
     * @param id the value for cc_asset.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.cid
     *
     * @return the value of cc_asset.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.cid
     *
     * @param cid the value for cc_asset.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.name
     *
     * @return the value of cc_asset.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.name
     *
     * @param name the value for cc_asset.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.symbol
     *
     * @return the value of cc_asset.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.symbol
     *
     * @param symbol the value for cc_asset.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.slug
     *
     * @return the value of cc_asset.slug
     *
     * @mbggenerated
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.slug
     *
     * @param slug the value for cc_asset.slug
     *
     * @mbggenerated
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.num_market_pairs
     *
     * @return the value of cc_asset.num_market_pairs
     *
     * @mbggenerated
     */
    public String getNumMarketPairs() {
        return numMarketPairs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.num_market_pairs
     *
     * @param numMarketPairs the value for cc_asset.num_market_pairs
     *
     * @mbggenerated
     */
    public void setNumMarketPairs(String numMarketPairs) {
        this.numMarketPairs = numMarketPairs == null ? null : numMarketPairs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.circulating_supply
     *
     * @return the value of cc_asset.circulating_supply
     *
     * @mbggenerated
     */
    public String getCirculatingSupply() {
        return circulatingSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.circulating_supply
     *
     * @param circulatingSupply the value for cc_asset.circulating_supply
     *
     * @mbggenerated
     */
    public void setCirculatingSupply(String circulatingSupply) {
        this.circulatingSupply = circulatingSupply == null ? null : circulatingSupply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.total_supply
     *
     * @return the value of cc_asset.total_supply
     *
     * @mbggenerated
     */
    public String getTotalSupply() {
        return totalSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.total_supply
     *
     * @param totalSupply the value for cc_asset.total_supply
     *
     * @mbggenerated
     */
    public void setTotalSupply(String totalSupply) {
        this.totalSupply = totalSupply == null ? null : totalSupply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.max_supply
     *
     * @return the value of cc_asset.max_supply
     *
     * @mbggenerated
     */
    public String getMaxSupply() {
        return maxSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.max_supply
     *
     * @param maxSupply the value for cc_asset.max_supply
     *
     * @mbggenerated
     */
    public void setMaxSupply(String maxSupply) {
        this.maxSupply = maxSupply == null ? null : maxSupply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.quote_price
     *
     * @return the value of cc_asset.quote_price
     *
     * @mbggenerated
     */
    public String getQuotePrice() {
        return quotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.quote_price
     *
     * @param quotePrice the value for cc_asset.quote_price
     *
     * @mbggenerated
     */
    public void setQuotePrice(String quotePrice) {
        this.quotePrice = quotePrice == null ? null : quotePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.quote_volume_24h
     *
     * @return the value of cc_asset.quote_volume_24h
     *
     * @mbggenerated
     */
    public String getQuoteVolume24h() {
        return quoteVolume24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.quote_volume_24h
     *
     * @param quoteVolume24h the value for cc_asset.quote_volume_24h
     *
     * @mbggenerated
     */
    public void setQuoteVolume24h(String quoteVolume24h) {
        this.quoteVolume24h = quoteVolume24h == null ? null : quoteVolume24h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.quote_percent_change_1h
     *
     * @return the value of cc_asset.quote_percent_change_1h
     *
     * @mbggenerated
     */
    public String getQuotePercentChange1h() {
        return quotePercentChange1h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.quote_percent_change_1h
     *
     * @param quotePercentChange1h the value for cc_asset.quote_percent_change_1h
     *
     * @mbggenerated
     */
    public void setQuotePercentChange1h(String quotePercentChange1h) {
        this.quotePercentChange1h = quotePercentChange1h == null ? null : quotePercentChange1h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.quote_percent_change_24h
     *
     * @return the value of cc_asset.quote_percent_change_24h
     *
     * @mbggenerated
     */
    public String getQuotePercentChange24h() {
        return quotePercentChange24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.quote_percent_change_24h
     *
     * @param quotePercentChange24h the value for cc_asset.quote_percent_change_24h
     *
     * @mbggenerated
     */
    public void setQuotePercentChange24h(String quotePercentChange24h) {
        this.quotePercentChange24h = quotePercentChange24h == null ? null : quotePercentChange24h.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.quote_percent_change_7d
     *
     * @return the value of cc_asset.quote_percent_change_7d
     *
     * @mbggenerated
     */
    public String getQuotePercentChange7d() {
        return quotePercentChange7d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.quote_percent_change_7d
     *
     * @param quotePercentChange7d the value for cc_asset.quote_percent_change_7d
     *
     * @mbggenerated
     */
    public void setQuotePercentChange7d(String quotePercentChange7d) {
        this.quotePercentChange7d = quotePercentChange7d == null ? null : quotePercentChange7d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.quote_market_cap
     *
     * @return the value of cc_asset.quote_market_cap
     *
     * @mbggenerated
     */
    public String getQuoteMarketCap() {
        return quoteMarketCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.quote_market_cap
     *
     * @param quoteMarketCap the value for cc_asset.quote_market_cap
     *
     * @mbggenerated
     */
    public void setQuoteMarketCap(String quoteMarketCap) {
        this.quoteMarketCap = quoteMarketCap == null ? null : quoteMarketCap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_asset.last_updated
     *
     * @return the value of cc_asset.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_asset.last_updated
     *
     * @param lastUpdated the value for cc_asset.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}