package com.chain.wp.coin.entity;

import java.io.Serializable;
import java.util.Date;

public class BtcMonitorRateHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.base_symbol
     *
     * @mbggenerated
     */
    private String baseSymbol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_aud
     *
     * @mbggenerated
     */
    private Double priceAud;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_brl
     *
     * @mbggenerated
     */
    private Double priceBrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_gbp
     *
     * @mbggenerated
     */
    private Double priceGbp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_cad
     *
     * @mbggenerated
     */
    private Double priceCad;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_clp
     *
     * @mbggenerated
     */
    private Double priceClp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_cny
     *
     * @mbggenerated
     */
    private Double priceCny;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_czk
     *
     * @mbggenerated
     */
    private Double priceCzk;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_dkk
     *
     * @mbggenerated
     */
    private Double priceDkk;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_eur
     *
     * @mbggenerated
     */
    private Double priceEur;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_hkd
     *
     * @mbggenerated
     */
    private Double priceHkd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_huf
     *
     * @mbggenerated
     */
    private Double priceHuf;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_inr
     *
     * @mbggenerated
     */
    private Double priceInr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_idr
     *
     * @mbggenerated
     */
    private Double priceIdr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_ils
     *
     * @mbggenerated
     */
    private Double priceIls;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_jpy
     *
     * @mbggenerated
     */
    private Double priceJpy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_myr
     *
     * @mbggenerated
     */
    private Double priceMyr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_mxn
     *
     * @mbggenerated
     */
    private Double priceMxn;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_twd
     *
     * @mbggenerated
     */
    private Double priceTwd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_nzd
     *
     * @mbggenerated
     */
    private Double priceNzd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_nok
     *
     * @mbggenerated
     */
    private Double priceNok;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_pkr
     *
     * @mbggenerated
     */
    private Double pricePkr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_php
     *
     * @mbggenerated
     */
    private Double pricePhp;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_pln
     *
     * @mbggenerated
     */
    private Double pricePln;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_rub
     *
     * @mbggenerated
     */
    private Double priceRub;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_sgd
     *
     * @mbggenerated
     */
    private Double priceSgd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_zar
     *
     * @mbggenerated
     */
    private Double priceZar;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_krw
     *
     * @mbggenerated
     */
    private Double priceKrw;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_sek
     *
     * @mbggenerated
     */
    private Double priceSek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_chf
     *
     * @mbggenerated
     */
    private Double priceChf;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_thb
     *
     * @mbggenerated
     */
    private Double priceThb;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_try
     *
     * @mbggenerated
     */
    private Double priceTry;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.price_usd
     *
     * @mbggenerated
     */
    private Double priceUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.volume_24h_usd
     *
     * @mbggenerated
     */
    private Double volume24hUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.percent_change_1h_usd
     *
     * @mbggenerated
     */
    private Double percentChange1hUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.percent_change_24h_usd
     *
     * @mbggenerated
     */
    private Double percentChange24hUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.percent_change_7d_usd
     *
     * @mbggenerated
     */
    private Double percentChange7dUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.market_cap_usd
     *
     * @mbggenerated
     */
    private Double marketCapUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_rate_history.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * cc_btc_monitor_rate_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.id
     *
     * @return the value of cc_btc_monitor_rate_history.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.id
     *
     * @param id the value for cc_btc_monitor_rate_history.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.base_symbol
     *
     * @return the value of cc_btc_monitor_rate_history.base_symbol
     *
     * @mbggenerated
     */
    public String getBaseSymbol() {
        return baseSymbol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.base_symbol
     *
     * @param baseSymbol the value for cc_btc_monitor_rate_history.base_symbol
     *
     * @mbggenerated
     */
    public void setBaseSymbol(String baseSymbol) {
        this.baseSymbol = baseSymbol == null ? null : baseSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_aud
     *
     * @return the value of cc_btc_monitor_rate_history.price_aud
     *
     * @mbggenerated
     */
    public Double getPriceAud() {
        return priceAud;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_aud
     *
     * @param priceAud the value for cc_btc_monitor_rate_history.price_aud
     *
     * @mbggenerated
     */
    public void setPriceAud(Double priceAud) {
        this.priceAud = priceAud;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_brl
     *
     * @return the value of cc_btc_monitor_rate_history.price_brl
     *
     * @mbggenerated
     */
    public Double getPriceBrl() {
        return priceBrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_brl
     *
     * @param priceBrl the value for cc_btc_monitor_rate_history.price_brl
     *
     * @mbggenerated
     */
    public void setPriceBrl(Double priceBrl) {
        this.priceBrl = priceBrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_gbp
     *
     * @return the value of cc_btc_monitor_rate_history.price_gbp
     *
     * @mbggenerated
     */
    public Double getPriceGbp() {
        return priceGbp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_gbp
     *
     * @param priceGbp the value for cc_btc_monitor_rate_history.price_gbp
     *
     * @mbggenerated
     */
    public void setPriceGbp(Double priceGbp) {
        this.priceGbp = priceGbp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_cad
     *
     * @return the value of cc_btc_monitor_rate_history.price_cad
     *
     * @mbggenerated
     */
    public Double getPriceCad() {
        return priceCad;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_cad
     *
     * @param priceCad the value for cc_btc_monitor_rate_history.price_cad
     *
     * @mbggenerated
     */
    public void setPriceCad(Double priceCad) {
        this.priceCad = priceCad;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_clp
     *
     * @return the value of cc_btc_monitor_rate_history.price_clp
     *
     * @mbggenerated
     */
    public Double getPriceClp() {
        return priceClp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_clp
     *
     * @param priceClp the value for cc_btc_monitor_rate_history.price_clp
     *
     * @mbggenerated
     */
    public void setPriceClp(Double priceClp) {
        this.priceClp = priceClp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_cny
     *
     * @return the value of cc_btc_monitor_rate_history.price_cny
     *
     * @mbggenerated
     */
    public Double getPriceCny() {
        return priceCny;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_cny
     *
     * @param priceCny the value for cc_btc_monitor_rate_history.price_cny
     *
     * @mbggenerated
     */
    public void setPriceCny(Double priceCny) {
        this.priceCny = priceCny;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_czk
     *
     * @return the value of cc_btc_monitor_rate_history.price_czk
     *
     * @mbggenerated
     */
    public Double getPriceCzk() {
        return priceCzk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_czk
     *
     * @param priceCzk the value for cc_btc_monitor_rate_history.price_czk
     *
     * @mbggenerated
     */
    public void setPriceCzk(Double priceCzk) {
        this.priceCzk = priceCzk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_dkk
     *
     * @return the value of cc_btc_monitor_rate_history.price_dkk
     *
     * @mbggenerated
     */
    public Double getPriceDkk() {
        return priceDkk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_dkk
     *
     * @param priceDkk the value for cc_btc_monitor_rate_history.price_dkk
     *
     * @mbggenerated
     */
    public void setPriceDkk(Double priceDkk) {
        this.priceDkk = priceDkk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_eur
     *
     * @return the value of cc_btc_monitor_rate_history.price_eur
     *
     * @mbggenerated
     */
    public Double getPriceEur() {
        return priceEur;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_eur
     *
     * @param priceEur the value for cc_btc_monitor_rate_history.price_eur
     *
     * @mbggenerated
     */
    public void setPriceEur(Double priceEur) {
        this.priceEur = priceEur;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_hkd
     *
     * @return the value of cc_btc_monitor_rate_history.price_hkd
     *
     * @mbggenerated
     */
    public Double getPriceHkd() {
        return priceHkd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_hkd
     *
     * @param priceHkd the value for cc_btc_monitor_rate_history.price_hkd
     *
     * @mbggenerated
     */
    public void setPriceHkd(Double priceHkd) {
        this.priceHkd = priceHkd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_huf
     *
     * @return the value of cc_btc_monitor_rate_history.price_huf
     *
     * @mbggenerated
     */
    public Double getPriceHuf() {
        return priceHuf;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_huf
     *
     * @param priceHuf the value for cc_btc_monitor_rate_history.price_huf
     *
     * @mbggenerated
     */
    public void setPriceHuf(Double priceHuf) {
        this.priceHuf = priceHuf;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_inr
     *
     * @return the value of cc_btc_monitor_rate_history.price_inr
     *
     * @mbggenerated
     */
    public Double getPriceInr() {
        return priceInr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_inr
     *
     * @param priceInr the value for cc_btc_monitor_rate_history.price_inr
     *
     * @mbggenerated
     */
    public void setPriceInr(Double priceInr) {
        this.priceInr = priceInr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_idr
     *
     * @return the value of cc_btc_monitor_rate_history.price_idr
     *
     * @mbggenerated
     */
    public Double getPriceIdr() {
        return priceIdr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_idr
     *
     * @param priceIdr the value for cc_btc_monitor_rate_history.price_idr
     *
     * @mbggenerated
     */
    public void setPriceIdr(Double priceIdr) {
        this.priceIdr = priceIdr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_ils
     *
     * @return the value of cc_btc_monitor_rate_history.price_ils
     *
     * @mbggenerated
     */
    public Double getPriceIls() {
        return priceIls;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_ils
     *
     * @param priceIls the value for cc_btc_monitor_rate_history.price_ils
     *
     * @mbggenerated
     */
    public void setPriceIls(Double priceIls) {
        this.priceIls = priceIls;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_jpy
     *
     * @return the value of cc_btc_monitor_rate_history.price_jpy
     *
     * @mbggenerated
     */
    public Double getPriceJpy() {
        return priceJpy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_jpy
     *
     * @param priceJpy the value for cc_btc_monitor_rate_history.price_jpy
     *
     * @mbggenerated
     */
    public void setPriceJpy(Double priceJpy) {
        this.priceJpy = priceJpy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_myr
     *
     * @return the value of cc_btc_monitor_rate_history.price_myr
     *
     * @mbggenerated
     */
    public Double getPriceMyr() {
        return priceMyr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_myr
     *
     * @param priceMyr the value for cc_btc_monitor_rate_history.price_myr
     *
     * @mbggenerated
     */
    public void setPriceMyr(Double priceMyr) {
        this.priceMyr = priceMyr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_mxn
     *
     * @return the value of cc_btc_monitor_rate_history.price_mxn
     *
     * @mbggenerated
     */
    public Double getPriceMxn() {
        return priceMxn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_mxn
     *
     * @param priceMxn the value for cc_btc_monitor_rate_history.price_mxn
     *
     * @mbggenerated
     */
    public void setPriceMxn(Double priceMxn) {
        this.priceMxn = priceMxn;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_twd
     *
     * @return the value of cc_btc_monitor_rate_history.price_twd
     *
     * @mbggenerated
     */
    public Double getPriceTwd() {
        return priceTwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_twd
     *
     * @param priceTwd the value for cc_btc_monitor_rate_history.price_twd
     *
     * @mbggenerated
     */
    public void setPriceTwd(Double priceTwd) {
        this.priceTwd = priceTwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_nzd
     *
     * @return the value of cc_btc_monitor_rate_history.price_nzd
     *
     * @mbggenerated
     */
    public Double getPriceNzd() {
        return priceNzd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_nzd
     *
     * @param priceNzd the value for cc_btc_monitor_rate_history.price_nzd
     *
     * @mbggenerated
     */
    public void setPriceNzd(Double priceNzd) {
        this.priceNzd = priceNzd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_nok
     *
     * @return the value of cc_btc_monitor_rate_history.price_nok
     *
     * @mbggenerated
     */
    public Double getPriceNok() {
        return priceNok;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_nok
     *
     * @param priceNok the value for cc_btc_monitor_rate_history.price_nok
     *
     * @mbggenerated
     */
    public void setPriceNok(Double priceNok) {
        this.priceNok = priceNok;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_pkr
     *
     * @return the value of cc_btc_monitor_rate_history.price_pkr
     *
     * @mbggenerated
     */
    public Double getPricePkr() {
        return pricePkr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_pkr
     *
     * @param pricePkr the value for cc_btc_monitor_rate_history.price_pkr
     *
     * @mbggenerated
     */
    public void setPricePkr(Double pricePkr) {
        this.pricePkr = pricePkr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_php
     *
     * @return the value of cc_btc_monitor_rate_history.price_php
     *
     * @mbggenerated
     */
    public Double getPricePhp() {
        return pricePhp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_php
     *
     * @param pricePhp the value for cc_btc_monitor_rate_history.price_php
     *
     * @mbggenerated
     */
    public void setPricePhp(Double pricePhp) {
        this.pricePhp = pricePhp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_pln
     *
     * @return the value of cc_btc_monitor_rate_history.price_pln
     *
     * @mbggenerated
     */
    public Double getPricePln() {
        return pricePln;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_pln
     *
     * @param pricePln the value for cc_btc_monitor_rate_history.price_pln
     *
     * @mbggenerated
     */
    public void setPricePln(Double pricePln) {
        this.pricePln = pricePln;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_rub
     *
     * @return the value of cc_btc_monitor_rate_history.price_rub
     *
     * @mbggenerated
     */
    public Double getPriceRub() {
        return priceRub;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_rub
     *
     * @param priceRub the value for cc_btc_monitor_rate_history.price_rub
     *
     * @mbggenerated
     */
    public void setPriceRub(Double priceRub) {
        this.priceRub = priceRub;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_sgd
     *
     * @return the value of cc_btc_monitor_rate_history.price_sgd
     *
     * @mbggenerated
     */
    public Double getPriceSgd() {
        return priceSgd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_sgd
     *
     * @param priceSgd the value for cc_btc_monitor_rate_history.price_sgd
     *
     * @mbggenerated
     */
    public void setPriceSgd(Double priceSgd) {
        this.priceSgd = priceSgd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_zar
     *
     * @return the value of cc_btc_monitor_rate_history.price_zar
     *
     * @mbggenerated
     */
    public Double getPriceZar() {
        return priceZar;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_zar
     *
     * @param priceZar the value for cc_btc_monitor_rate_history.price_zar
     *
     * @mbggenerated
     */
    public void setPriceZar(Double priceZar) {
        this.priceZar = priceZar;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_krw
     *
     * @return the value of cc_btc_monitor_rate_history.price_krw
     *
     * @mbggenerated
     */
    public Double getPriceKrw() {
        return priceKrw;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_krw
     *
     * @param priceKrw the value for cc_btc_monitor_rate_history.price_krw
     *
     * @mbggenerated
     */
    public void setPriceKrw(Double priceKrw) {
        this.priceKrw = priceKrw;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_sek
     *
     * @return the value of cc_btc_monitor_rate_history.price_sek
     *
     * @mbggenerated
     */
    public Double getPriceSek() {
        return priceSek;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_sek
     *
     * @param priceSek the value for cc_btc_monitor_rate_history.price_sek
     *
     * @mbggenerated
     */
    public void setPriceSek(Double priceSek) {
        this.priceSek = priceSek;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_chf
     *
     * @return the value of cc_btc_monitor_rate_history.price_chf
     *
     * @mbggenerated
     */
    public Double getPriceChf() {
        return priceChf;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_chf
     *
     * @param priceChf the value for cc_btc_monitor_rate_history.price_chf
     *
     * @mbggenerated
     */
    public void setPriceChf(Double priceChf) {
        this.priceChf = priceChf;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_thb
     *
     * @return the value of cc_btc_monitor_rate_history.price_thb
     *
     * @mbggenerated
     */
    public Double getPriceThb() {
        return priceThb;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_thb
     *
     * @param priceThb the value for cc_btc_monitor_rate_history.price_thb
     *
     * @mbggenerated
     */
    public void setPriceThb(Double priceThb) {
        this.priceThb = priceThb;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_try
     *
     * @return the value of cc_btc_monitor_rate_history.price_try
     *
     * @mbggenerated
     */
    public Double getPriceTry() {
        return priceTry;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_try
     *
     * @param priceTry the value for cc_btc_monitor_rate_history.price_try
     *
     * @mbggenerated
     */
    public void setPriceTry(Double priceTry) {
        this.priceTry = priceTry;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.price_usd
     *
     * @return the value of cc_btc_monitor_rate_history.price_usd
     *
     * @mbggenerated
     */
    public Double getPriceUsd() {
        return priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.price_usd
     *
     * @param priceUsd the value for cc_btc_monitor_rate_history.price_usd
     *
     * @mbggenerated
     */
    public void setPriceUsd(Double priceUsd) {
        this.priceUsd = priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.volume_24h_usd
     *
     * @return the value of cc_btc_monitor_rate_history.volume_24h_usd
     *
     * @mbggenerated
     */
    public Double getVolume24hUsd() {
        return volume24hUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.volume_24h_usd
     *
     * @param volume24hUsd the value for cc_btc_monitor_rate_history.volume_24h_usd
     *
     * @mbggenerated
     */
    public void setVolume24hUsd(Double volume24hUsd) {
        this.volume24hUsd = volume24hUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.percent_change_1h_usd
     *
     * @return the value of cc_btc_monitor_rate_history.percent_change_1h_usd
     *
     * @mbggenerated
     */
    public Double getPercentChange1hUsd() {
        return percentChange1hUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.percent_change_1h_usd
     *
     * @param percentChange1hUsd the value for cc_btc_monitor_rate_history.percent_change_1h_usd
     *
     * @mbggenerated
     */
    public void setPercentChange1hUsd(Double percentChange1hUsd) {
        this.percentChange1hUsd = percentChange1hUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.percent_change_24h_usd
     *
     * @return the value of cc_btc_monitor_rate_history.percent_change_24h_usd
     *
     * @mbggenerated
     */
    public Double getPercentChange24hUsd() {
        return percentChange24hUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.percent_change_24h_usd
     *
     * @param percentChange24hUsd the value for cc_btc_monitor_rate_history.percent_change_24h_usd
     *
     * @mbggenerated
     */
    public void setPercentChange24hUsd(Double percentChange24hUsd) {
        this.percentChange24hUsd = percentChange24hUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.percent_change_7d_usd
     *
     * @return the value of cc_btc_monitor_rate_history.percent_change_7d_usd
     *
     * @mbggenerated
     */
    public Double getPercentChange7dUsd() {
        return percentChange7dUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.percent_change_7d_usd
     *
     * @param percentChange7dUsd the value for cc_btc_monitor_rate_history.percent_change_7d_usd
     *
     * @mbggenerated
     */
    public void setPercentChange7dUsd(Double percentChange7dUsd) {
        this.percentChange7dUsd = percentChange7dUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.market_cap_usd
     *
     * @return the value of cc_btc_monitor_rate_history.market_cap_usd
     *
     * @mbggenerated
     */
    public Double getMarketCapUsd() {
        return marketCapUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.market_cap_usd
     *
     * @param marketCapUsd the value for cc_btc_monitor_rate_history.market_cap_usd
     *
     * @mbggenerated
     */
    public void setMarketCapUsd(Double marketCapUsd) {
        this.marketCapUsd = marketCapUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.last_updated
     *
     * @return the value of cc_btc_monitor_rate_history.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.last_updated
     *
     * @param lastUpdated the value for cc_btc_monitor_rate_history.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.create_date
     *
     * @return the value of cc_btc_monitor_rate_history.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.create_date
     *
     * @param createDate the value for cc_btc_monitor_rate_history.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_rate_history.update_date
     *
     * @return the value of cc_btc_monitor_rate_history.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_rate_history.update_date
     *
     * @param updateDate the value for cc_btc_monitor_rate_history.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}
