package com.chain.wp.coin.entity;

import java.io.Serializable;
import java.util.Date;

public class BtcMonitorOhlcvHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.base_symbol
     *
     * @mbggenerated
     */
    private String baseSymbol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.quote_symbol
     *
     * @mbggenerated
     */
    private String quoteSymbol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.open
     *
     * @mbggenerated
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.high
     *
     * @mbggenerated
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.low
     *
     * @mbggenerated
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.close
     *
     * @mbggenerated
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.volume
     *
     * @mbggenerated
     */
    private Double volume;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_ohlcv_history.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * cc_btc_monitor_ohlcv_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.id
     *
     * @return the value of cc_btc_monitor_ohlcv_history.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.id
     *
     * @param id the value for cc_btc_monitor_ohlcv_history.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.base_symbol
     *
     * @return the value of cc_btc_monitor_ohlcv_history.base_symbol
     *
     * @mbggenerated
     */
    public String getBaseSymbol() {
        return baseSymbol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.base_symbol
     *
     * @param baseSymbol the value for cc_btc_monitor_ohlcv_history.base_symbol
     *
     * @mbggenerated
     */
    public void setBaseSymbol(String baseSymbol) {
        this.baseSymbol = baseSymbol == null ? null : baseSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.quote_symbol
     *
     * @return the value of cc_btc_monitor_ohlcv_history.quote_symbol
     *
     * @mbggenerated
     */
    public String getQuoteSymbol() {
        return quoteSymbol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.quote_symbol
     *
     * @param quoteSymbol the value for cc_btc_monitor_ohlcv_history.quote_symbol
     *
     * @mbggenerated
     */
    public void setQuoteSymbol(String quoteSymbol) {
        this.quoteSymbol = quoteSymbol == null ? null : quoteSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.open
     *
     * @return the value of cc_btc_monitor_ohlcv_history.open
     *
     * @mbggenerated
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.open
     *
     * @param open the value for cc_btc_monitor_ohlcv_history.open
     *
     * @mbggenerated
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.high
     *
     * @return the value of cc_btc_monitor_ohlcv_history.high
     *
     * @mbggenerated
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.high
     *
     * @param high the value for cc_btc_monitor_ohlcv_history.high
     *
     * @mbggenerated
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.low
     *
     * @return the value of cc_btc_monitor_ohlcv_history.low
     *
     * @mbggenerated
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.low
     *
     * @param low the value for cc_btc_monitor_ohlcv_history.low
     *
     * @mbggenerated
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.close
     *
     * @return the value of cc_btc_monitor_ohlcv_history.close
     *
     * @mbggenerated
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.close
     *
     * @param close the value for cc_btc_monitor_ohlcv_history.close
     *
     * @mbggenerated
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.volume
     *
     * @return the value of cc_btc_monitor_ohlcv_history.volume
     *
     * @mbggenerated
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.volume
     *
     * @param volume the value for cc_btc_monitor_ohlcv_history.volume
     *
     * @mbggenerated
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.last_updated
     *
     * @return the value of cc_btc_monitor_ohlcv_history.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.last_updated
     *
     * @param lastUpdated the value for cc_btc_monitor_ohlcv_history.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.create_date
     *
     * @return the value of cc_btc_monitor_ohlcv_history.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.create_date
     *
     * @param createDate the value for cc_btc_monitor_ohlcv_history.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_ohlcv_history.update_date
     *
     * @return the value of cc_btc_monitor_ohlcv_history.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_ohlcv_history.update_date
     *
     * @param updateDate the value for cc_btc_monitor_ohlcv_history.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}
