package com.chain.wp.coin.entity;

import java.io.Serializable;
import java.util.Date;

public class BtcMonitorLineHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.base_symbol
     *
     * @mbggenerated
     */
    private String baseSymbol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.price_jpy
     *
     * @mbggenerated
     */
    private Double priceJpy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.price_usd
     *
     * @mbggenerated
     */
    private Double priceUsd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.price_eur
     *
     * @mbggenerated
     */
    private Double priceEur;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.price_cny
     *
     * @mbggenerated
     */
    private Double priceCny;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.last_updated
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * cc_btc_monitor_line_history.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * cc_btc_monitor_line_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.id
     *
     * @return the value of cc_btc_monitor_line_history.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.id
     *
     * @param id the value for cc_btc_monitor_line_history.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.base_symbol
     *
     * @return the value of cc_btc_monitor_line_history.base_symbol
     *
     * @mbggenerated
     */
    public String getBaseSymbol() {
        return baseSymbol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.base_symbol
     *
     * @param baseSymbol the value for cc_btc_monitor_line_history.base_symbol
     *
     * @mbggenerated
     */
    public void setBaseSymbol(String baseSymbol) {
        this.baseSymbol = baseSymbol == null ? null : baseSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.price_jpy
     *
     * @return the value of cc_btc_monitor_line_history.price_jpy
     *
     * @mbggenerated
     */
    public Double getPriceJpy() {
        return priceJpy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.price_jpy
     *
     * @param priceJpy the value for cc_btc_monitor_line_history.price_jpy
     *
     * @mbggenerated
     */
    public void setPriceJpy(Double priceJpy) {
        this.priceJpy = priceJpy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.price_usd
     *
     * @return the value of cc_btc_monitor_line_history.price_usd
     *
     * @mbggenerated
     */
    public Double getPriceUsd() {
        return priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.price_usd
     *
     * @param priceUsd the value for cc_btc_monitor_line_history.price_usd
     *
     * @mbggenerated
     */
    public void setPriceUsd(Double priceUsd) {
        this.priceUsd = priceUsd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.price_eur
     *
     * @return the value of cc_btc_monitor_line_history.price_eur
     *
     * @mbggenerated
     */
    public Double getPriceEur() {
        return priceEur;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.price_eur
     *
     * @param priceEur the value for cc_btc_monitor_line_history.price_eur
     *
     * @mbggenerated
     */
    public void setPriceEur(Double priceEur) {
        this.priceEur = priceEur;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.price_cny
     *
     * @return the value of cc_btc_monitor_line_history.price_cny
     *
     * @mbggenerated
     */
    public Double getPriceCny() {
        return priceCny;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.price_cny
     *
     * @param priceCny the value for cc_btc_monitor_line_history.price_cny
     *
     * @mbggenerated
     */
    public void setPriceCny(Double priceCny) {
        this.priceCny = priceCny;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.last_updated
     *
     * @return the value of cc_btc_monitor_line_history.last_updated
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.last_updated
     *
     * @param lastUpdated the value for cc_btc_monitor_line_history.last_updated
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.create_date
     *
     * @return the value of cc_btc_monitor_line_history.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.create_date
     *
     * @param createDate the value for cc_btc_monitor_line_history.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column cc_btc_monitor_line_history.update_date
     *
     * @return the value of cc_btc_monitor_line_history.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * cc_btc_monitor_line_history.update_date
     *
     * @param updateDate the value for cc_btc_monitor_line_history.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}
