package com.chain.wp.coin.entity;

import java.io.Serializable;

public class LegalCurrency implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_legalcurrency.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_legalcurrency.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_legalcurrency.en_name
     *
     * @mbggenerated
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_legalcurrency.jp_name
     *
     * @mbggenerated
     */
    private String jpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_legalcurrency.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_legalcurrency.is_actived
     *
     * @mbggenerated
     */
    private String isActived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cc_legalcurrency
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_legalcurrency.id
     *
     * @return the value of cc_legalcurrency.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_legalcurrency.id
     *
     * @param id the value for cc_legalcurrency.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_legalcurrency.name
     *
     * @return the value of cc_legalcurrency.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_legalcurrency.name
     *
     * @param name the value for cc_legalcurrency.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_legalcurrency.en_name
     *
     * @return the value of cc_legalcurrency.en_name
     *
     * @mbggenerated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_legalcurrency.en_name
     *
     * @param enName the value for cc_legalcurrency.en_name
     *
     * @mbggenerated
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_legalcurrency.jp_name
     *
     * @return the value of cc_legalcurrency.jp_name
     *
     * @mbggenerated
     */
    public String getJpName() {
        return jpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_legalcurrency.jp_name
     *
     * @param jpName the value for cc_legalcurrency.jp_name
     *
     * @mbggenerated
     */
    public void setJpName(String jpName) {
        this.jpName = jpName == null ? null : jpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_legalcurrency.symbol
     *
     * @return the value of cc_legalcurrency.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_legalcurrency.symbol
     *
     * @param symbol the value for cc_legalcurrency.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_legalcurrency.is_actived
     *
     * @return the value of cc_legalcurrency.is_actived
     *
     * @mbggenerated
     */
    public String getIsActived() {
        return isActived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_legalcurrency.is_actived
     *
     * @param isActived the value for cc_legalcurrency.is_actived
     *
     * @mbggenerated
     */
    public void setIsActived(String isActived) {
        this.isActived = isActived == null ? null : isActived.trim();
    }
}